services:
  - type: web
    name: aligo-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: OTP_TTL_MINUTES
        value: "5"
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_MINIAPP_URL
        sync: false
